### PR TITLE
support for atlas query, status update, OLM basics

### PR DESCRIPTION
**Pull request by jeremyary**

### CODE REVIEW

**Comment by jeremyary** [comment]
@jianrongzhang89 going to go ahead and merge up so we can move forward with work we need to get through for the week, but an FYI this is out here if we want to have some convo on it.

**Comment by wtrocki** [comment]
@jeremyary is this runablle right now? Can I take look

**Comment by jeremyary** [comment]
@wtrocki It is! I've got it deployed and running on our lab, happy to show you there on a quick vid chat or google chat me and I can walk you thru make commands and what resource you'll need to create to trigger it if you'd like. The functionality is not fully there yet for creating the resource that we'll be "binding" against, though that's coming soon. Thus far, it's all about querying Atlas and getting instance info back to allow the admin to select from in a mock UI.

**Comment by wtrocki** [comment]
Thank you. Will check code and we can have some Dev sync later

**Pull request merged**
