### PR TITLE
Updated the architectural diagram, screenshots, and procedures

### PR DESCRIPTION
**Pull request by ritz303**
## Description
Updated the architectural diagram showing the OpenShift Database Access components, and the screenshots in the the "Creating a DBaaSInventory" and "Creating a DBaaSConnection" sections.  Also, updated the steps in those procedures.

## Type of change
- [ ] Diagram update
- [ ] Screenshot updates
- [ ] Content updates

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Review by tchughesiv — CHANGES_REQUESTED** [review]
thanks for the contrib! looking good so far... any chance we could change the other 2 images w/ mongo references as well?

**Review by jianrongzhang89 — APPROVED** [review]
lgtm

**Comment by ritz303** [comment]
@tchughesiv : I'd have to spin up an OCP environment and recapture those screen.  So, it maybe another day or two before I can do that, unless someone else already has an environment where they can recapture those screens.

**Comment by redhatHameed** [comment]
@ritz303 we can remove the the OCP telemetry plugin section from diagram as this was used previously and we removed from dbaas code.

**Comment by ritz303** [comment]
@redhatHameed : Thanks for the feedback!  I'll remove the telemetry plugin from the diagram.

**Comment by redhatHameed** [comment]
> @redhatHameed : Thanks for the feedback! I'll remove the telemetry plugin from the diagram.

@ritz303 thanks for updating it, will be great if we can add steps for creating the instance steps with screenshot if not added

**Comment by ritz303** [comment]
> @ritz303 thanks for updating it, will be great if we can add steps for creating the instance steps with screenshot if not added

@redhatHameed : I like the suggestion, but that sounds out-of-scope for this PR.  Please feel free to create an issue, and assign it to me.  I'll try to spend some time working on it over the next week or so.

**Review by redhatHameed — APPROVED** [review]

**Review by ritz303 — COMMENTED** [review]
> thanks for the contrib! looking good so far... any chance we could change the other 2 images w/ mongo references as well?

@tchughesiv : This was in response to your requested changes.  I've updated the screenshots, where MongoDB was referenced.

**Review by tchughesiv — APPROVED** [review]
lgtm

**Pull request merged**
