### PR TITLE
Updated the code to add/remove finalizer to dbaasplatform CR

### PR DESCRIPTION
**Pull request by xieshenzh**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Review by jeremyary — DISMISSED** [review]

**Comment by jianrongzhang89** [comment]
@xieshenzh could you let me know why this PR is needed? Thanks

**Comment by xieshenzh** [comment]
> @xieshenzh could you let me know why this PR is needed? Thanks

The catalog needs old bundles to upgrade the operator. Modified the makefile to include the old bundles when building the index image.
Also modified the name of the finalizer and use `controllerutil` to add/remove with finalizer.

**Comment by redhatHameed** [comment]
@xieshenzh what if the old bundle not exists,  let suppose developer building the image first time. I am getting this error while I don't old bundle in quay.io 
```
make catalog-build
getting below errors
ERRO[0003] Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally
Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown  bundles="[quay.io/ahameed/dbaas-operator-bundle:v0.1.1 quay.io/ahameed/dbaas-operator-bundle:v0.1.0]"
ERRO[0003] permissive mode disabled                      bundles="[quay.io/ahameed/dbaas-operator-bundle:v0.1.1 quay.io/ahameed/dbaas-operator-bundle:v0.1.0]" error="[error pulling image: Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown\n. exit status 1, error creating container Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally\nError response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown\n: exit status 1]"
Error: [error pulling image: Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown
. exit status 1, error creating container Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally
Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown
: exit status 1]```

**Comment by xieshenzh** [comment]
> @xieshenzh what if the old bundle not exists, let suppose developer building the image first time. I am getting this error while I don't have old bundle in quay.io
> 
> ```
> make catalog-build
> getting below errors
> ERRO[0003] Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally
> Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown  bundles="[quay.io/ahameed/dbaas-operator-bundle:v0.1.1 quay.io/ahameed/dbaas-operator-bundle:v0.1.0]"
> ERRO[0003] permissive mode disabled                      bundles="[quay.io/ahameed/dbaas-operator-bundle:v0.1.1 quay.io/ahameed/dbaas-operator-bundle:v0.1.0]" error="[error pulling image: Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown\n. exit status 1, error creating container Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally\nError response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown\n: exit status 1]"
> Error: [error pulling image: Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown
> . exit status 1, error creating container Unable to find image 'quay.io/ahameed/dbaas-operator-bundle:v0.1.0' locally
> Error response from daemon: manifest for quay.io/ahameed/dbaas-operator-bundle:v0.1.0 not found: manifest unknown: manifest unknown
> : exit status 1]```
> ```

Added check if old bundles are set.

@redhatHameed since you changed the quay repo, you can also unset the old bundles, or use the old bundles from `quay.io/ecosystem-appeng/dbaas-operator-bundle`, or tag and push the old bundles to your repo `quay.io/ahameed/dbaas-operator-bundle`.

**Review by redhatHameed — APPROVED** [review]

**Comment by jeremyary** [comment]
@xieshenzh I'm working the Makefile changes into another PR to version up to `0.1.2` today. Can you modify this PR to just be the finalizer changes, please? I don't want to lose those. Thanks!!

**Comment by xieshenzh** [comment]
Close this PR, will merge the changes of this PR to https://github.com/RHEcosystemAppEng/dbaas-operator/pull/64.

**Pull request closed without merging**
