### PR TITLE
upgrade observability-operator library and go version

### PR DESCRIPTION
**Pull request by tchughesiv**
Signed-off-by: Tommy Hughes <tohughes@redhat.com>

required for https://github.com/RHEcosystemAppEng/dbaas-operator/pull/297

version upgrades in this PR - 
- go -> 1.18
- ubi8-minimal -> 8.7
- operator-sdk -> 1.22.2
- kustomize -> 4.5.7
- envtest -> 1.25.0
- k8s.io libraries -> 0.25.4
- gosec -> 2.12.0

### CODE REVIEW

**Comment by tchughesiv** [comment]
@redhatHameed is this what you need? if so, we can merge and you can build on top?

**Comment by redhatHameed** [comment]
> Member

@tchughesiv thanks, Just minor change upgrading GoSec version as ```        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.14.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0```

**Comment by tchughesiv** [comment]
> > Member
> 
> @tchughesiv thanks, Just minor change upgrading GoSec version as ` run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.14.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0`

ya, i had already done `2.12.0` ... let me know if there's a req to do to 2.14

**Comment by redhatHameed** [comment]
> > > Member
> > 
> > 
> > @tchughesiv thanks, Just minor change upgrading GoSec version as ` run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.14.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0`
> 
> ya, i had already done `2.12.0` ... let me know if there's a req to do to 2.14

`2.12.0` also work, Thanks

**Comment by redhatHameed** [comment]
@tchughesiv we can merge this, I will continue my PR on that .

**Pull request merged**
