### PR TITLE
[DBAAS-1092] Remove logging from setConnectionStatusMetrics

### PR DESCRIPTION
**Pull request by rhkp**
## Description
Remove logging from setConnectionStatusMetrics as it generates too much of logs

## Verification Steps
The multiple logs from setConnectionStatusMetrics should not appear, as they are deleted

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by redhatHameed** [comment]
@rhkp how about other objects like platform as seen in attached logs 

[dbaas-operator-controller-manager-7f6c76bcb-r942m-manager (5).log](https://github.com/RHEcosystemAppEng/dbaas-operator/files/10246767/dbaas-operator-controller-manager-7f6c76bcb-r942m-manager.5.log)

**Comment by rhkp** [comment]
I agree. I do not know why would DBaaSPlatform reconciliation is almost being happening continually? And that is why the logs are appearing more frequently.

Wait let remove from DBaaSPlatform logs as well. Give me a few minutes.

**Comment by rhkp** [comment]
Thanks @redhatHameed. Please check now and approve/merge. Thanks.

**Comment by redhatHameed** [comment]
@rhkp thanks,

can you share the pods logs with these changes. Also you can you create the different objects like inventory, connection , instance and see how is the frequency of log generation,

**Comment by rhkp** [comment]
Okay, sure. 
I still will keep a few logs if they are not too frequent. But let us check and remove the frequent ones.

**Comment by rhkp** [comment]
@redhatHameed Please check now, I have removed "too frequent" logs. 

[rhkp-2-dbaas-operator-controller-manager-dbcf846fc-mrj7m-manager.log](https://github.com/RHEcosystemAppEng/dbaas-operator/files/10247817/rhkp-2-dbaas-operator-controller-manager-dbcf846fc-mrj7m-manager.log)

**Comment by redhatHameed** [comment]
> Okay, sure. 
> 
> I still will keep a few logs if they are not too frequent. But let us check and remove the frequent ones.

Thanks 
WDYT removing these'
INFO	Inventory Request Duration for event: create	Set the request duration for create event,

**Comment by rhkp** [comment]
> > Okay, sure.
> > I still will keep a few logs if they are not too frequent. But let us check and remove the frequent ones.
> 
> Thanks WDYT removing these' INFO Inventory Request Duration for event: create Set the request duration for create event,

Hi Abdul, I think I would like to keep it for now, as this is new. Let us keep these until the features are stabilized, for next release or two.

**Comment by redhatHameed** [comment]
> > > Okay, sure.
> 
> > > I still will keep a few logs if they are not too frequent. But let us check and remove the frequent ones.
> 
> > 
> 
> > Thanks WDYT removing these' INFO Inventory Request Duration for event: create Set the request duration for create event,
> 
> 
> 
> Hi Abdul, I think I would like to keep it for now, as this is new. Let us keep these until the features are stabilized, for next release or two.

Sure, let's create a Jira and assign it, so we can revisit this in future.

**Review by redhatHameed — APPROVED** [review]

**Comment by rhkp** [comment]
No worries. I have this Jira which we will take up sometime March/April 2023 hopefully, by when we will know if these features are stable enough.

https://issues.redhat.com/browse/DBAAS-1103

Can you approve and merge the PR now?

**Pull request merged**
