### PR TITLE
adding initial metrics

### PR DESCRIPTION
**Pull request by redhatHameed**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist (Definition of Done)

- [ ] All acceptance criteria specified in JIRA or in issue number have been completed
- [ ] Unit tests added that prove the fix is effective or the feature works 
- [ ] Documentation added for the feature
- [ ] all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by redhatHameed** [comment]
@jianrongzhang89 see here I have disabled kube-proxy and able to see the metrics -> https://github.com/RHEcosystemAppEng/dbaas-operator/pull/51/commits/d2b813e42b88554040b6e6271902c8c979879199

**Comment by redhatHameed** [comment]
Screen Shot 2021-10-06 at 2 44 48 PM

**Comment by tchughesiv** [comment]
@redhatHameed rebase on main to resolve the lint errors

**Comment by redhatHameed** [comment]
closing this PR as no more needs

**Pull request closed without merging**
