### PR TITLE
[DBAAS-413] remove console-telemetry-plugin from RHODA stack

### PR DESCRIPTION
**Pull request by tchughesiv**
console-telemetry-plugin is no longer in use and should be removed from the project now.

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

### CODE REVIEW

**Review by redhatHameed — APPROVED** [review]
LGTM

**Comment by jeremyary** [comment]
@olavtar are you aware of any code in the osd-e2e that may be specifically referencing the console-telemetry-plugin? Not sure if it was included in added validations or not.

**Comment by olavtar** [comment]
> @olavtar are you aware of any code in the osd-e2e that may be specifically referencing the console-telemetry-plugin? Not sure if it was included in added validations or not.

@jeremyary I don't believe there is any code to reference the console-telemetry-plugin. I definitely did not add it.

**Comment by jeremyary** [comment]
> > @olavtar are you aware of any code in the osd-e2e that may be specifically referencing the console-telemetry-plugin? Not sure if it was included in added validations or not.
> 
> @jeremyary I don't believe there is any code to reference the console-telemetry-plugin. I definitely did not add it.

ok great, thanks!!

**Review by jeremyary — APPROVED** [review]

**Review by jianrongzhang89 — APPROVED** [review]
OK

**Pull request merged**
